### PR TITLE
Update _package.json

### PR DESCRIPTION
**Pull request by dmfilipenko**
Remove nodeunit

### CODE REVIEW

**Comment by MrDHat** [comment]
Leaving nodeunit in package.json was a big blunder! Thanks for fixing.
Just update the commit message to a more helpful one and we'll be good to go!

**Comment by dmfilipenko** [comment]
Change npm module nodeunit to mocha in package.json

**Comment by MrDHat** [comment]
I meant the commit message.
Update the 'commit' message to something like your comment. `Update _package.json` is not a helpful commit message.
(Same goes for the other PR)

**Comment by dmfilipenko** [comment]
I think, it's impossible or make hard reset to overwrite commit message

**Comment by MrDHat** [comment]
Do this to update your last commit message: `git commit --amend -m '<New Commit message>'`

**Comment by dmfilipenko** [comment]
All done:)

**Comment by MrDHat** [comment]
I still see 4 different commits. The first commit still says `Update _package.json`
Why not do this:
- Add a commit to remove repetition
- Add another commit for removing nodeunit

How does that sound? I think creating a new branch with a new PR might be a better option here instead of wasting energy on correcting this one.
I am closing this and the other PR and eagerly waiting for the new one to merge :)

**Pull request closed without merging**
