### PR TITLE
add LICENSE file

### PR DESCRIPTION
**Pull request by thanpolas**

### CODE REVIEW

**Comment by MrDHat** [comment]
The type of license (if used) depends highly on the type of project. For eg: you wouldn't need to add a license if you are building a web app which isn't going to be open-sourced.
I don't think that we should force a license through the generator.

**Comment by thanpolas** [comment]
I'll prompt the user with the option... 

Next pass i'll integrate yeoman's store API so i'll revisit this PR then

**Comment by MrDHat** [comment]
Since, yeoman asks for a license during the initialization process, hence, we should grab the license from there and generate the license file accordingly.

**Comment by thanpolas** [comment]
So i run the generator today, and noticed that we DO ask for LICENSE: 

> The name of your project shouldn't contain "node" or "js" and
> should be a unique ID not already in use at search.npmjs.org.
> [?] Module Name: noddd
> [?] Description: The best module ever.
> [?] Homepage: 
> [?] License: MIT

Didn't look any deeper though, how do you handle this?

**Comment by MrDHat** [comment]
`yo` (or `generator-generator`) handles this internally.

**Comment by thanpolas** [comment]
great news then, i'll have a deeper look when i have some time

**Comment by MrDHat** [comment]
It might be a nice idea to add a license automatically based on the selection (in generator-generator or yo wherever the license is prompted).

**Pull request closed without merging**
